# Run the backend on port 8080
server.port=8080

# MongoDB Connection String (Assuming local MongoDB. The database 'ipcadb' will be created automatically)
spring.data.mongodb.uri=mongodb://localhost:27017/ipcadb